#include "hw/ws2812_output.h"

#include <stdio.h>

#include "hardware/dma.h"
#include "hardware/pio.h"

#include "ws2812.pio.h" /* generated by pico_generate_pio_header (CMakeLists.txt) - flat, not under hw/ */
#include "pico_config.h"

#define WS2812_FREQ_HZ 800000.0f

/* Fixed pin assignment, identical on every board - see
 * docs/docs/pico-device.md, "same firmware everywhere". Change here (not per
 * build) if the wiring convention ever changes; every existing board would
 * need rewiring to match. */
static const uint LED_PINS[PICO_NUM_LED_PINS] = {2, 3};

typedef struct {
    PIO pio;
    uint sm;
    int dma_chan;
    uint32_t packed[PICO_MAX_PIXELS_PER_PIN];
} channel_t;

static channel_t channels[PICO_NUM_LED_PINS];

void ws2812_output_init(void) {
    for (int i = 0; i < PICO_NUM_LED_PINS; i++) {
        channel_t *c = &channels[i];
        c->pio = pio0;
        c->sm = (uint)i;

        uint offset = pio_add_program(c->pio, &ws2812_program);
        ws2812_program_init(c->pio, c->sm, offset, LED_PINS[i], WS2812_FREQ_HZ);

        c->dma_chan = dma_claim_unused_channel(true);
        dma_channel_config cfg = dma_channel_get_default_config(c->dma_chan);
        channel_config_set_transfer_data_size(&cfg, DMA_SIZE_32);
        channel_config_set_read_increment(&cfg, true);
        channel_config_set_write_increment(&cfg, false);
        channel_config_set_dreq(&cfg, pio_get_dreq(c->pio, c->sm, true));
        dma_channel_configure(c->dma_chan, &cfg, &c->pio->txf[c->sm], NULL, 0, false);

        /* one-time, core0-only - confirms the PIO/DMA setup actually ran and
         * which physical pin each channel drives, before anything else could
         * mask a hardware init failure as "no LEDs" further down the line */
        printf("ws2812: channel %d on GPIO %u (pio%d sm%u, dma chan %d)\n",
               i, LED_PINS[i], c->pio == pio0 ? 0 : 1, c->sm, c->dma_chan);
    }

    ws2812_output_blank();
}

static void pack_channel(channel_t *c, const uint8_t *rgb, uint16_t pixel_count) {
    for (uint16_t i = 0; i < pixel_count; i++) {
        uint8_t r = rgb[i * 3 + 0];
        uint8_t g = rgb[i * 3 + 1];
        uint8_t b = rgb[i * 3 + 2];
        /* GRB, left-justified in the top 24 bits for the PIO program's
         * autopull (see ws2812.pio) */
        c->packed[i] = ((uint32_t)g << 24) | ((uint32_t)r << 16) | ((uint32_t)b << 8);
    }
}

static void show_channel(channel_t *c, uint16_t pixel_count) {
    dma_channel_wait_for_finish_blocking(c->dma_chan); /* the previous transfer, if any, must be done first */
    dma_channel_set_read_addr(c->dma_chan, c->packed, false);
    dma_channel_set_trans_count(c->dma_chan, pixel_count, true);
}

void ws2812_output_show(const uint8_t *rgb, uint16_t payload_len) {
    uint16_t total_pixels = payload_len / 3;

    for (int i = 0; i < PICO_NUM_LED_PINS; i++) {
        uint16_t start = (uint16_t)(i * PICO_MAX_PIXELS_PER_PIN);
        if (start >= total_pixels) {
            show_channel(&channels[i], 0);
            continue;
        }

        uint16_t count = total_pixels - start;
        if (count > PICO_MAX_PIXELS_PER_PIN) count = PICO_MAX_PIXELS_PER_PIN;

        pack_channel(&channels[i], rgb + start * 3, count);
        show_channel(&channels[i], count);
    }
}

void ws2812_output_blank(void) {
    static const uint8_t zero[PICO_MAX_PIXELS_TOTAL * 3] = {0};
    ws2812_output_show(zero, sizeof(zero));
}
